export const questions=[
    {question: "What is the name of the protagonist in 'Naruto'?", option1: "Sasuke Uchiha", option2: "Naruto Uzumaki", option3: "Sakura Haruno", option4: "Kakashi Hatake", ans: 2},
    {question: "In 'Attack on Titan', what are the giant humanoid creatures called?", option1: "Titans", option2: "Kaiju", option3: "Shinigami", option4: "Kitsune", ans: 1},
    {question: "Which anime features a character named Goku?", option1: "One Piece", option2: "Dragon Ball", option3: "Bleach", option4: "Naruto", ans: 2},
    {question: "What is the name of the magical school in 'Harry Potter'?", option1: "Hogwarts", option2: "Beauxbatons", option3: "Durmstrang", option4: "Ilvermorny", ans: 1},
    {question: "In 'My Hero Academia', what is Izuku Midoriya's hero name?", option1: "Deku", option2: "All Might", option3: "Endeavor", option4: "Shoto", ans: 1},
    {question: "In 'One Piece', what is Luffy's dream?", option1: "To become the Pirate King", option2: "To find the One Piece", option3: "To be the strongest swordsman", option4: "To control the seas", ans: 1},
    {question: "What is the primary goal of Edward and Alphonse Elric in 'Fullmetal Alchemist'?", option1: "To become state alchemists", option2: "To find the Philosopher's Stone", option3: "To defeat the Homunculi", option4: "To save their mother", ans: 2},
    {question: "In 'Death Note', what is the name of the Shinigami who drops the Death Note?", option1: "Ryuk", option2: "Rem", option3: "Sosuke", option4: "Shido", ans: 1},
    {question: "What is the setting of 'Cowboy Bebop'?", option1: "Space", option2: "Medieval Japan", option3: "Post-apocalyptic Earth", option4: "A fantasy world", ans: 1},
    {question: "Who is the creator of 'Neon Genesis Evangelion'?", option1: "Hideaki Anno", option2: "Satoshi Kon", option3: "Yoko Kanno", option4: "Makoto Shinkai", ans: 1},
    {question: "In 'Sword Art Online', what is the name of the virtual reality MMORPG?", option1: "Alfheim Online", option2: "Gun Gale Online", option3: "Sword Art Online", option4: "New World Online", ans: 3},
    {question: "In 'One Punch Man', who is the main character known for defeating enemies with one punch?", option1: "Saitama", option2: "Genos", option3: "Mumen Rider", option4: "Bang", ans: 1},
    {question: "In 'Tokyo Ghoul', what is Kaneki Ken transformed into after the surgery?", option1: "Ghoul", option2: "Half-Ghoul", option3: "Human", option4: "Demon", ans: 2},
    {question: "In 'My Neighbor Totoro', what are the creatures that Totoro looks after?", option1: "Spirits", option2: "Fairies", option3: "Dragons", option4: "Kitsune", ans: 1},
    {question: "In 'Attack on Titan', who is the leader of the Survey Corps?", option1: "Levi Ackerman", option2: "Erwin Smith", option3: "Armin Arlert", option4: "Jean Kirstein", ans: 2},
    {question: "In 'Bleach', what is Ichigo Kurosaki's primary role?", option1: "Soul Reaper", option2: "Shinigami", option3: "Vizard", option4: "Arrancar", ans: 1},
    {question: "What is the main character's name in 'Cowboy Bebop'?", option1: "Spike Spiegel", option2: "Jet Black", option3: "Faye Valentine", option4: "Edward Wong", ans: 1},
    {question: "In 'Naruto', what is the name of Naruto's demon fox?", option1: "Kurama", option2: "Shukaku", option3: "Gyuki", option4: "Kokuo", ans: 1},
    {question: "In 'Dragon Ball Z', who is Goku's main rival?", option1: "Vegeta", option2: "Frieza", option3: "Cell", option4: "Majin Buu", ans: 1},
    {question: "What is the name of the main character in 'Bleach' who has a Zanpakuto named Zangetsu?", option1: "Ichigo Kurosaki", option2: "Renji Abarai", option3: "Rukia Kuchiki", option4: "Uryu Ishida", ans: 1},
    {question: "In 'Fullmetal Alchemist', which country is the setting of the story?", option1: "Germany", option2: "Ishval", option3: "Amestris", option4: "Xerxes", ans: 3},
    {question: "In 'Death Note', who is the main antagonist who opposes Light Yagami?", option1: "L", option2: "Near", option3: "Mello", option4: "Ryuk", ans: 1},
    {question: "What is the name of the series featuring a cat-like creature named Luna?", option1: "Sailor Moon", option2: "Inuyasha", option3: "Cardcaptor Sakura", option4: "Fruits Basket", ans: 1},
    {question: "In 'Neon Genesis Evangelion', what are the giant mechs called?", option1: "Angels", option2: "Evangelions", option3: "Titans", option4: "Gundams", ans: 2},
    {question: "Who is the author of the manga 'One Piece'?", option1: "Masashi Kishimoto", option2: "Akira Toriyama", option3: "Eiichiro Oda", option4: "Hirohiko Araki", ans: 3},
    {question: "In 'Sword Art Online', what is the name of Kirito's main love interest?", option1: "Suguha Kirigaya", option2: "Asuna Yuuki", option3: "Sinon", option4: "Leafa", ans: 2},
    {question: "In 'My Hero Academia', what is All Might's real name?", option1: "Toshinori Yagi", option2: "Ken Ishimura", option3: "Shota Aizawa", option4: "Ryoji Kageyama", ans: 1},
    {question: "In 'Cowboy Bebop', which character is a skilled hacker and member of the Bebop crew?", option1: "Faye Valentine", option2: "Jet Black", option3: "Edward Wong", option4: "Spike Spiegel", ans: 3},
    {question: "In 'Attack on Titan', which character can transform into a giant armored titan?", option1: "Eren Yeager", option2: "Reiner Braun", option3: "Annie Leonhart", option4: "Bertolt Fubar", ans: 2},
    {question: "In 'Fruits Basket', which animal does Tohru Honda accidentally hug that causes a transformation?", option1: "Cat", option2: "Dog", option3: "Rat", option4: "Horse", ans: 1},
    {question: "What is the name of the demon-slaying swordsman in 'Inuyasha'?", option1: "Kagome Higurashi", option2: "Sesshomaru", option3: "Inuyasha", option4: "Miroku", ans: 3},
    {question: "In 'Naruto', who is the leader of the Akatsuki?", option1: "Orochimaru", option2: "Pain", option3: "Itachi Uchiha", option4: "Madara Uchiha", ans: 2},
    {question: "In 'One Piece', who is the swordsman of the Straw Hat Pirates?", option1: "Monkey D. Luffy", option2: "Roronoa Zoro", option3: "Sanji", option4: "Nami", ans: 2},
    {question: "In 'Tokyo Ghoul', what is the name of the organization fighting ghouls?", option1: "CCG", option2: "GOG", option3: "FBI", option4: "UN", ans: 1},
    {question: "In 'Demon Slayer', what is Tanjiro Kamado's weapon of choice?", option1: "Sword", option2: "Axe", option3: "Bow and Arrow", option4: "Spear", ans: 1},
    {question: "In 'My Hero Academia', what is the name of the hero agency run by Endeavor?", option1: "Fire Hero Agency", option2: "Hero Association", option3: "Flame Hero Office", option4: "Endeavor Hero Agency", ans: 4},
    {question: "What anime features a character named Luffy who searches for the ultimate treasure?", option1: "One Piece", option2: "Naruto", option3: "Bleach", option4: "Fairy Tail", ans: 1},
    {question: "In 'Death Note', what is the real name of the character known as 'Light Yagami'?", option1: "Light Yagami", option2: "L", option3: "Ryuk", option4: "Near", ans: 1},
    {question: "In 'Cowboy Bebop', which character is a former police officer and the ship's mechanic?", option1: "Jet Black", option2: "Faye Valentine", option3: "Spike Spiegel", option4: "Edward Wong", ans: 1},
    {question: "In 'Attack on Titan', what is the name of Eren's adoptive sister?", option1: "Mikasa Ackerman", option2: "Annie Leonhart", option3: "Hange Zoë", option4: "Historia Reiss", ans: 1},
    {question: "In 'Fullmetal Alchemist', what is the name of the alchemical symbol that represents human transmutation?", option1: "Transmutation Circle", option2: "Pentagram", option3: "Homunculus Mark", option4: "Philosopher's Stone", ans: 1},
    {question: "In 'Bleach', which character is known as the 'Goddess of Death'?", option1: "Rukia Kuchiki", option2: "Orihime Inoue", option3: "Yoruichi Shihouin", option4: "Tatsuki Arisawa", ans: 3},
    {question: "In 'One Punch Man', who is Saitama's disciple?", option1: "Mumen Rider", option2: "Genos", option3: "Bang", option4: "Silver Fang", ans: 2},
    {question: "What is the name of the main character in 'Naruto' who is a ninja with dreams of becoming Hokage?", option1: "Sasuke Uchiha", option2: "Naruto Uzumaki", option3: "Sakura Haruno", option4: "Kakashi Hatake", ans: 2},
    {question: "In 'Sword Art Online', who is Kirito's younger sister?", option1: "Asuna Yuuki", option2: "Suguha Kirigaya", option3: "Sinon", option4: "Leafa", ans: 2},
    {question: "In 'Death Note', who is the second person to use the Death Note after Light Yagami?", option1: "Misa Amane", option2: "Near", option3: "Mello", option4: "Ryuk", ans: 1},
    {question: "In 'Tokyo Ghoul', what is the name of the main organization Kaneki Ken joins?", option1: "Aogiri Tree", option2: "Antique Shop", option3: "CCG", option4: "Black Market", ans: 1},
    {question: "In 'My Hero Academia', what is the name of the hero agency that is based on the concept of 'Stain'?", option1: "Hero Killer Agency", option2: "Hero Association", option3: "Vigilante Agency", option4: "Stain's League", ans: 1},
    {question: "In 'Cowboy Bebop', what is the name of Spike Spiegel's former syndicate?", option1: "Red Dragon", option2: "White Fang", option3: "Black Lotus", option4: "Blue Star", ans: 1},
    {question: "In 'Fullmetal Alchemist', who is the leader of the Homunculi?", option1: "Envy", option2: "Gluttony", option3: "Pride", option4: "Father", ans: 4},
    {question: "In 'Naruto', who is known as the 'Copy Ninja'?", option1: "Obito Uchiha", option2: "Sasuke Uchiha", option3: "Kakashi Hatake", option4: "Minato Namikaze", ans: 3},
    {question: "In 'One Piece', what is the name of the treasure that Luffy seeks?", option1: "One Piece", option2: "Devil Fruit", option3: "Grand Line", option4: "Nakama", ans: 1},
    {question: "In 'My Hero Academia', who is the principal of U.A. High School?", option1: "Aizawa Shota", option2: "All Might", option3: "Nezu", option4: "Gran Torino", ans: 3},
    {question: "In 'Demon Slayer', what is the name of Tanjiro's sister who turns into a demon?", option1: "Nezuko Kamado", option2: "Mitsuri Kanroji", option3: "Kanao Tsuyuri", option4: "Shinobu Kocho", ans: 1},
    {question: "In 'Attack on Titan', what is the name of the city where humanity first fights against the Titans?", option1: "Wall Maria", option2: "Wall Rose", option3: "Wall Sina", option4: "Paradise Island", ans: 3},
    {question: "In 'Bleach', which character is known for wielding the sword 'Zangetsu'?", option1: "Ichigo Kurosaki", option2: "Renji Abarai", option3: "Kisuke Urahara", option4: "Rukia Kuchiki", ans: 1},
    {question: "In 'One Punch Man', who is known as the hero with the most recognition?", option1: "Saitama", option2: "Genos", option3: "Mumen Rider", option4: "Tornado of Terror", ans: 4},
    {question: "In 'Neon Genesis Evangelion', who pilots EVA Unit-01?", option1: "Shinji Ikari", option2: "Rei Ayanami", option3: "Asuka Langley", option4: "Misato Katsuragi", ans: 1},
    {question: "In 'Sword Art Online', what is the name of the virtual world in which players are trapped?", option1: "Alfheim Online", option2: "Gun Gale Online", option3: "Sword Art Online", option4: "The Underworld", ans: 3},
    {question: "In 'Cowboy Bebop', which character is known for their love of gambling and debt?", option1: "Jet Black", option2: "Faye Valentine", option3: "Spike Spiegel", option4: "Edward Wong", ans: 2},
    {question: "In 'Fullmetal Alchemist', which metal is central to the story's alchemical process?", option1: "Gold", option2: "Silver", option3: "Iron", option4: "Aluminum", ans: 1},
    {question: "In 'Tokyo Ghoul', what is the name of Kaneki Ken's best friend who becomes a ghoul?", option1: "Hideyoshi Nagachika", option2: "Rize Kamishiro", option3: "Touka Kirishima", option4: "Ken Kaneki", ans: 1},
    {question: "In 'My Hero Academia', who is the student known for the power of 'Explosion'?", option1: "Katsuki Bakugo", option2: "Izuku Midoriya", option3: "Shoto Todoroki", option4: "Tenya Iida", ans: 1},
    {question: "In 'One Piece', which character is known for his strong sense of justice and is a Marine Admiral?", option1: "Akainu", option2: "Aokiji", option3: "Kizaru", option4: "Sengoku", ans: 1},
    {question: "In 'Naruto', who is the leader of the Akatsuki group that seeks to capture all Tailed Beasts?", option1: "Nagato", option2: "Itachi Uchiha", option3: "Obito Uchiha", option4: "Madara Uchiha", ans: 1},
    {question: "In 'Attack on Titan', which character has the power of the Female Titan?", option1: "Annie Leonhart", option2: "Hange Zoë", option3: "Erwin Smith", option4: "Mikasa Ackerman", ans: 1},
    {question: "In 'Fullmetal Alchemist', who is the 'Steel Alchemist'?", option1: "Roy Mustang", option2: "Edward Elric", option3: "Alphonse Elric", option4: "Jean Havoc", ans: 2},
    {question: "In 'Death Note', what is the name of Light Yagami's notebook?", option1: "Death Note", option2: "Shinigami's Journal", option3: "Notebook of Death", option4: "Ryuk's Book", ans: 1},]
    