export const questions=[
    {question: "What is the capital city of Japan?", option1: "Yokohama", option2: "Osaka", option3: "Nagoya", option4: "Tokyo", ans: 4},
{question: "What is the largest planet in our solar system?", option1: "Earth", option2: "Mars", option3: "Jupiter", option4: "Saturn", ans: 3},
{question: "Who wrote the play 'Romeo and Juliet'?", option1: "William Shakespeare", option2: "Charles Dickens", option3: "Jane Austen", option4: "Mark Twain", ans: 1},
{question: "What is the chemical symbol for gold?", option1: "Au", option2: "Ag", option3: "Pb", option4: "Fe", ans: 1},
{question: "Which ocean is the largest?", option1: "Atlantic Ocean", option2: "Indian Ocean", option3: "Arctic Ocean", option4: "Pacific Ocean", ans: 4},
{question: "What year did the Titanic sink?", option1: "1912", option2: "1905", option3: "1898", option4: "1923", ans: 1},
{question: "What is the hardest natural substance on Earth?", option1: "Gold", option2: "Iron", option3: "Diamond", option4: "Platinum", ans: 3},
{question: "What is the smallest country in the world by land area?", option1: "Monaco", option2: "San Marino", option3: "Vatican City", option4: "Liechtenstein", ans: 3},
{question: "Who painted the Mona Lisa?", option1: "Vincent van Gogh", option2: "Pablo Picasso", option3: "Leonardo da Vinci", option4: "Claude Monet", ans: 3},
{question: "Which element has the atomic number 1?", option1: "Helium", option2: "Hydrogen", option3: "Oxygen", option4: "Carbon", ans: 2},
{question: "What is the capital of Australia?", option1: "Sydney", option2: "Melbourne", option3: "Brisbane", option4: "Canberra", ans: 4},
{question: "What is the tallest mountain in the world?", option1: "K2", option2: "Kangchenjunga", option3: "Mount Everest", option4: "Lhotse", ans: 3},
{question: "What is the main ingredient in guacamole?", option1: "Tomato", option2: "Pepper", option3: "Avocado", option4: "Onion", ans: 3},
{question: "Who is known as the Father of Physics?", option1: "Isaac Newton", option2: "Albert Einstein", option3: "Galileo Galilei", option4: "Niels Bohr", ans: 1},
{question: "What is the largest organ in the human body?", option1: "Heart", option2: "Liver", option3: "Lungs", option4: "Skin", ans: 4},
{question: "What is the chemical formula for water?", option1: "CO2", option2: "H2O", option3: "NaCl", option4: "O2", ans: 2},
{question: "Which planet is known as the Red Planet?", option1: "Venus", option2: "Mars", option3: "Mercury", option4: "Jupiter", ans: 2},
{question: "Who wrote 'Pride and Prejudice'?", option1: "Emily Brontë", option2: "Charlotte Brontë", option3: "Jane Austen", option4: "Mary Shelley", ans: 3},
{question: "In what country is the Great Barrier Reef located?", option1: "Philippines", option2: "Australia", option3: "Indonesia", option4: "Thailand", ans: 2},
{question: "What is the capital of France?", option1: "Paris", option2: "Rome", option3: "Madrid", option4: "Berlin", ans: 1},
{question: "Which element is represented by the symbol 'Na'?", option1: "Neon", option2: "Nitrogen", option3: "Sodium", option4: "Nickel", ans: 3},
{question: "What is the main language spoken in Brazil?", option1: "Spanish", option2: "English", option3: "Portuguese", option4: "French", ans: 3},
{question: "Which famous scientist developed the theory of relativity?", option1: "Isaac Newton", option2: "Albert Einstein", option3: "Stephen Hawking", option4: "Galileo Galilei", ans: 2},
{question: "What is the capital of Italy?", option1: "Venice", option2: "Rome", option3: "Milan", option4: "Florence", ans: 2},
{question: "Who wrote 'The Catcher in the Rye'?", option1: "J.D. Salinger", option2: "Ernest Hemingway", option3: "F. Scott Fitzgerald", option4: "John Steinbeck", ans: 1},
{question: "What is the most abundant gas in Earth's atmosphere?", option1: "Oxygen", option2: "Carbon Dioxide", option3: "Nitrogen", option4: "Hydrogen", ans: 3},
{question: "What is the currency of Japan?", option1: "Yuan", option2: "Won", option3: "Yen", option4: "Ringgit", ans: 3},
{question: "What is the smallest bone in the human body?", option1: "Stapes", option2: "Femur", option3: "Tibia", option4: "Humerus", ans: 1},
{question: "Which country is known as the Land of the Rising Sun?", option1: "China", option2: "Japan", option3: "South Korea", option4: "Thailand", ans: 2},
{question: "What is the largest desert in the world?", option1: "Sahara", option2: "Gobi", option3: "Kalahari", option4: "Antarctic Desert", ans: 4},
{question: "Who is the author of the Harry Potter series?", option1: "J.K. Rowling", option2: "J.R.R. Tolkien", option3: "George R.R. Martin", option4: "C.S. Lewis", ans: 1},
{question: "What is the longest river in the world?", option1: "Amazon", option2: "Nile", option3: "Yangtze", option4: "Mississippi", ans: 2},
{question: "What is the chemical symbol for silver?", option1: "Ag", option2: "Au", option3: "Pb", option4: "Fe", ans: 1},
{question: "Which country is famous for its pyramids?", option1: "Greece", option2: "Egypt", option3: "Mexico", option4: "India", ans: 2},
{question: "What is the hardest natural substance on Earth?", option1: "Gold", option2: "Iron", option3: "Diamond", option4: "Platinum", ans: 3},
{question: "What is the speed of light?", option1: "300,000 km/s", option2: "150,000 km/s", option3: "450,000 km/s", option4: "600,000 km/s", ans: 1},
{question: "Who discovered penicillin?", option1: "Louis Pasteur", option2: "Alexander Fleming", option3: "Marie Curie", option4: "Robert Koch", ans: 2},
{question: "What is the capital of Canada?", option1: "Toronto", option2: "Vancouver", option3: "Montreal", option4: "Ottawa", ans: 4},
{question: "What is the most common element in the universe?", option1: "Oxygen", option2: "Carbon", option3: "Hydrogen", option4: "Helium", ans: 3},
{question: "Which ocean is the smallest?", option1: "Indian Ocean", option2: "Arctic Ocean", option3: "Atlantic Ocean", option4: "Pacific Ocean", ans: 2},
{question: "What is the chemical symbol for potassium?", option1: "K", option2: "P", option3: "Po", option4: "Pt", ans: 1},
{question: "What is the capital of Germany?", option1: "Berlin", option2: "Munich", option3: "Hamburg", option4: "Frankfurt", ans: 1},
{question: "Which artist is known for the 'Starry Night' painting?", option1: "Vincent van Gogh", option2: "Claude Monet", option3: "Pablo Picasso", option4: "Salvador Dalí", ans: 1}]
