export const questions = [
    {question: "What is the chemical symbol for Gold?", option1: "Au", option2: "Ag", option3: "Pb", option4: "Fe", ans: 1},
    {question: "Which element has the atomic number 1?", option1: "Hydrogen", option2: "Helium", option3: "Oxygen", option4: "Nitrogen", ans: 1},
    {question: "What is the chemical formula for water?", option1: "H2O", option2: "CO2", option3: "NaCl", option4: "O2", ans: 1},
    {question: "Which gas is most abundant in Earth's atmosphere?", option1: "Oxygen", option2: "Nitrogen", option3: "Carbon Dioxide", option4: "Hydrogen", ans: 2},
    {question: "What is the pH value of pure water at 25°C?", option1: "7", option2: "14", option3: "1", option4: "5", ans: 1},
    {question: "What is the chemical symbol for Silver?", option1: "Au", option2: "Ag", option3: "Si", option4: "Na", ans: 2},
    {question: "Which of the following is a noble gas?", option1: "Oxygen", option2: "Nitrogen", option3: "Argon", option4: "Chlorine", ans: 3},
    {question: "What is the name of the process where a liquid turns into a gas?", option1: "Melting", option2: "Condensation", option3: "Evaporation", option4: "Freezing", ans: 3},
    {question: "Which element is represented by the symbol 'Cl'?", option1: "Chlorine", option2: "Carbon", option3: "Calcium", option4: "Cobalt", ans: 1},
    {question: "What is the common name for sodium chloride?", option1: "Table Salt", option2: "Baking Soda", option3: "Epsom Salt", option4: "Bleach", ans: 1},
    {question: "Which element is the lightest metal?", option1: "Lithium", option2: "Sodium", option3: "Potassium", option4: "Calcium", ans: 1},
    {question: "What is the chemical formula for table sugar?", option1: "C6H12O6", option2: "C12H22O11", option3: "C6H10O5", option4: "C6H14O6", ans: 2},
    {question: "Which acid is found in vinegar?", option1: "Acetic Acid", option2: "Citric Acid", option3: "Lactic Acid", option4: "Sulfuric Acid", ans: 1},
    {question: "What is the chemical symbol for Iron?", option1: "Ir", option2: "Fe", option3: "I", option4: "In", ans: 2},
    {question: "Which element is essential for respiration?", option1: "Carbon", option2: "Hydrogen", option3: "Oxygen", option4: "Nitrogen", ans: 3},
    {question: "What is the main component of natural gas?", option1: "Methane", option2: "Ethane", option3: "Propane", option4: "Butane", ans: 1},
    {question: "Which element has the atomic number 8?", option1: "Nitrogen", option2: "Oxygen", option3: "Fluorine", option4: "Neon", ans: 2},
    {question: "What is the chemical formula for sulfuric acid?", option1: "H2SO4", option2: "HCl", option3: "HNO3", option4: "H2CO3", ans: 1},
    {question: "What is the process of converting a solid directly into a gas called?", option1: "Sublimation", option2: "Deposition", option3: "Condensation", option4: "Evaporation", ans: 1},
    {question: "What is the most reactive metal in the alkali metals group?", option1: "Lithium", option2: "Sodium", option3: "Potassium", option4: "Francium", ans: 4},
    {question: "Which element is commonly used in batteries?", option1: "Zinc", option2: "Iron", option3: "Copper", option4: "Nickel", ans: 1},
    {question: "What is the name of the bond formed between two nonmetals?", option1: "Ionic Bond", option2: "Metallic Bond", option3: "Covalent Bond", option4: "Hydrogen Bond", ans: 3},
    {question: "What is the chemical formula for ammonia?", option1: "NH3", option2: "NH4", option3: "N2H4", option4: "NO2", ans: 1},
    {question: "Which element is used in the production of stainless steel?", option1: "Nickel", option2: "Copper", option3: "Lead", option4: "Tin", ans: 1},
    {question: "What is the name of the reaction where an acid reacts with a base to form water and salt?", option1: "Oxidation", option2: "Neutralization", option3: "Combustion", option4: "Decomposition", ans: 2},
    {question: "Which gas is used in neon signs?", option1: "Neon", option2: "Krypton", option3: "Argon", option4: "Xenon", ans: 1},
    {question: "What is the main ingredient in limestone?", option1: "Calcium Carbonate", option2: "Calcium Oxide", option3: "Calcium Chloride", option4: "Calcium Sulfate", ans: 1},
    {question: "What is the name of the process where a substance is broken down by heat?", option1: "Thermolysis", option2: "Hydrolysis", option3: "Electrolysis", option4: "Photosynthesis", ans: 1},
    {question: "What is the chemical formula for methane?", option1: "CH4", option2: "C2H6", option3: "C3H8", option4: "C4H10", ans: 1},
    {question: "Which element is commonly used in fertilizers?", option1: "Potassium", option2: "Magnesium", option3: "Calcium", option4: "Boron", ans: 1},
    {question: "What is the process of separating a mixture based on different boiling points called?", option1: "Distillation", option2: "Filtration", option3: "Chromatography", option4: "Evaporation", ans: 1},
    {question: "Which element is known as the 'backbone' of organic chemistry?", option1: "Oxygen", option2: "Carbon", option3: "Hydrogen", option4: "Nitrogen", ans: 2},
    {question: "What is the chemical symbol for Helium?", option1: "He", option2: "H", option3: "Ho", option4: "Hl", ans: 1},
    {question: "What is the name of the process where a liquid changes into a gas?", option1: "Sublimation", option2: "Evaporation", option3: "Condensation", option4: "Freezing", ans: 2},
    {question: "What is the chemical formula for hydrochloric acid?", option1: "HCl", option2: "H2SO4", option3: "HNO3", option4: "CH3COOH", ans: 1},
    {question: "Which element is used to create red colors in fireworks?", option1: "Strontium", option2: "Barium", option3: "Copper", option4: "Calcium", ans: 1},
    {question: "What is the name of the bond formed by the transfer of electrons?", option1: "Covalent Bond", option2: "Ionic Bond", option3: "Metallic Bond", option4: "Hydrogen Bond", ans: 2},
    {question: "What is the chemical formula for ethanol?", option1: "C2H6O", option2: "C2H5OH", option3: "C3H7OH", option4: "C4H10O", ans: 2},
    {question: "Which element is commonly used in lightbulbs?", option1: "Tungsten", option2: "Iron", option3: "Copper", option4: "Silver", ans: 1},
    {question: "What is the chemical symbol for Potassium?", option1: "K", option2: "P", option3: "Po", option4: "Pt", ans: 1}]
